import turtle
import math
x1_rect1, x2_rect1, y1_rect1, y2_rect1= list(map(float, input("Введите координаты верхней левой и правой нижней вершин первого прямоугольника через пробел: ").split()))
x1_rect2, x2_rect2, y1_rect2, y2_rect2= list(map(float, input("Введите координаты верхней левой и правой нижней вершин второго прямоугольника через пробел: ").split()))
turtle.penup()
turtle.goto(x1_rect1, y1_rect1)
turtle.pendown()
turtle.pencolor('black')
turtle.forward(y2_rect1)
turtle.right(90)
turtle.forward(x2_rect1)
turtle.right(90)
turtle.forward(y2_rect1)
turtle.right(90)
turtle.forward(x2_rect1)
turtle.penup()
turtle.goto(x1_rect2, y1_rect2)
turtle.pendown()
turtle.pencolor('black')
turtle.forward(y2_rect2)
turtle.right(90)
turtle.forward(x2_rect2)
turtle.right(90)
turtle.forward(y2_rect2)
turtle.right(90)
turtle.forward(x2_rect2)
turtle.penup()
if x1_rect1 > x2_rect2 or x2_rect1 < x1_rect2 or y1_rect1 < y2_rect2 or y2_rect1 > y1_rect2:
    turtle.pendown()
    turtle.pencolor('red')
    turtle.write("Прямоугольники лежат вне друг друга, не касаясь")
elif x1_rect1 == x2_rect2 or x2_rect1 == x1_rect2 or y1_rect1 == y2_rect2 or y2_rect1 == y1_rect2:
    turtle.pendown()
    turtle.pencolor('red')
    turtle.write("Прямоугольники имеют касание")
else:
    turtle.pendown()
    turtle.pencolor('red')
    turtle.write("Прямоугольники имеют пересечение")
turtle.done()